version: '3'
services:

  backend:
    build: ./backend
    container_name: "chat-backend"
    ports:
      - 5000:5000

  frontend:
    build: ./frontend
    container_name: "chat-frontend"
    ports:
      - 3000:3000
    links:
      - backend
